### ISSUE TITLE
Veebilehe teema

### ISSUE THREAD

**Issue by taidopurason** [taidopurason/veebileht#1]
Pakkuge välja ideid, mille kohta võiks teha veebilehe.

**Comment by EduardNot** [comment]
Halval juhul saame teha, mingi loomast

**Comment by EduardNot** [comment]
Samas saame teha mingi programmeerimise keelest

**Comment by taidopurason** [comment]
Mul tuli üks idee. Ma kirjutasin javascripti ümber ühe [BZ](https://en.wikipedia.org/wiki/Belousov%E2%80%93Zhabotinsky_reaction) reaktsiooni simulatsiooni algoritmi. Kood on [*bz* branchis](https://github.com/taidopurason/veebileht/tree/bz) . Võiks selle kohta teha veebilehe.

[Siin](http://kodu.ut.ee/~taido/BZ/) on ka esialgne versioon algoritmist. 
Muide, see pole eriti optimaalne kood praegu suure ekraani jaoks, nii et ta töötab aeglaselt (simulatsioon näidatakse täiel lehe ulatusel). Aitab, kui lihtsalt browseri aken väiksemaks teha ja refreshida.

**Comment by jur-vol** [comment]
Mul hakkasid silmad valutama))))

вт, 6 нояб. 2018 г. в 12:34, taidopurason <notifications@github.com>:

**Comment by EduardNot** [comment]
Hei, meil on vaja teha wiki ka juba järgmiseks nädalaks.

**Comment by taidopurason** [comment]
Ma panen selle _issue_ kinni. Palun teeme iga probleemi jaoks eraldi _issue_, et asjad oleks organiseeritud.
